/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type { ThreeElements } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { Mesh, MeshStandardMaterial } from "three";
import { useLeafRustleAnimation } from "@/components/scene/useLeafRustleAnimation";
import {
  TreeRootFillMesh,
  type TreeRootMeshConfig,
} from "./TreeRootFillMesh";

const TREE_SMALL_V2_MODEL_PATH = "/models/tree_small_v2.glb";
const TREE_BASE_POSITION: [number, number, number] = [-35.432, 0, 311.575];
const TREE_OFFSET_FROM_BASE: [number, number, number] = [35.432, 0, -311.575];

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>;
  materials: Record<string, MeshStandardMaterial>;
};

type TreeSmallV2Props = ThreeElements["group"] & {
  growthScale?: number;
  rootsFillProgress?: number;
  rustleIntensity?: number;
};

const ROOT_MESHES: TreeRootMeshConfig[] = [
  { node: "Cube033", material: "Material.024", position: [-35.5, -0.515, 313.654], rotation: [0.489, 0, Math.PI], scale: [-0.198, -0.14, -0.186] },
  { node: "Cube034", material: "Material.025", position: [-35.45, -0.637, 312.977], rotation: [-2.73, 0, -Math.PI], scale: 0.12 },
  { node: "Cube035", material: "Material.026", position: [-35.456, -0.471, 312.864], rotation: [-0.803, 0, 0], scale: [0.202, 0.143, 0.19] },
  { node: "Cube037", material: "Material.028", position: [-35.455, -0.25, 312.19], rotation: [-0.685, 0, 0], scale: [0.191, 0.129, 0.176] },
  { node: "Cube041", material: "Material.032", position: [-35.432, -0.778, 311.094], rotation: [-2.561, 0, -Math.PI], scale: 0.195 },
  { node: "Cube042", material: "Material.033", position: [-35.398, -0.515, 311.465], rotation: [-1.054, 0, 0], scale: [0.487, 0.343, 0.456] },
  { node: "Cube043", material: "Material.034", position: [-35.354, -0.25, 310.08], rotation: [-0.694, 0, 0], scale: [0.578, 0.39, 0.533] },
  { node: "Cube044", material: "Material.035", position: [-35.36, -0.554, 313.135], rotation: [-2.73, 0, -Math.PI], scale: 0.49 },
  { node: "Cube047", material: "Material.038", position: [-35.396, -0.04, 310.762], rotation: [-0.249, 0, 0], scale: [0.487, 0.343, 0.456] },
  { node: "Cube048", material: "Material.039", position: [-35.393, 0.144, 311.194], rotation: [-0.62, 0, 0], scale: [0.646, 0.591, 0.786] },
  { node: "Cube049", material: "Material.040", position: [-35.432, -0.217, 311.9], rotation: [-2.113, 0.05, 3.067], scale: [0.481, 0.339, 0.451] },
  { node: "Cube050", material: "Material.041", position: [-35.393, 0.093, 312.186], rotation: [-2.522, 0, -Math.PI], scale: [0.646, 0.591, 0.786] },
  { node: "Cube051", material: "Material.042", position: [-35.402, 0.014, 310.225], rotation: [-0.141, 0, 0], scale: [0.721, 0.839, 0.839] },
  { node: "Cube052", material: "Material.043", position: [-35.41, 0.227, 313.044], rotation: [-3.041, 0, -Math.PI], scale: 0.643 },
];

export function TreeSmallV2({
  growthScale = 1,
  rootsFillProgress = 0,
  rustleIntensity = 0,
  ...props
}: TreeSmallV2Props) {
  const { nodes, materials } = useGLTF(
    TREE_SMALL_V2_MODEL_PATH,
  ) as unknown as GLTFResult;
  const leavesGroupRef = useLeafRustleAnimation({
    intensity: rustleIntensity,
    phaseOffset: 1.4,
  });

  return (
    <group {...props} dispose={null}>
      <group position={TREE_BASE_POSITION} scale={growthScale}>
        <group position={TREE_OFFSET_FROM_BASE} visible={false}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials['Material.024']}
        position={[-35.5, -0.515, 313.654]}
        rotation={[0.489, 0, Math.PI]}
        scale={[-0.198, -0.14, -0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials['Material.025']}
        position={[-35.45, -0.637, 312.977]}
        rotation={[-2.73, 0, -Math.PI]}
        scale={0.12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials['Material.026']}
        position={[-35.456, -0.471, 312.864]}
        rotation={[-0.803, 0, 0]}
        scale={[0.202, 0.143, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials['Material.028']}
        position={[-35.455, -0.25, 312.19]}
        rotation={[-0.685, 0, 0]}
        scale={[0.191, 0.129, 0.176]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials['Material.032']}
        position={[-35.432, -0.778, 311.094]}
        rotation={[-2.561, 0, -Math.PI]}
        scale={0.195}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials['Material.033']}
        position={[-35.398, -0.515, 311.465]}
        rotation={[-1.054, 0, 0]}
        scale={[0.487, 0.343, 0.456]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={materials['Material.034']}
        position={[-35.354, -0.25, 310.08]}
        rotation={[-0.694, 0, 0]}
        scale={[0.578, 0.39, 0.533]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={materials['Material.035']}
        position={[-35.36, -0.554, 313.135]}
        rotation={[-2.73, 0, -Math.PI]}
        scale={0.49}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047.geometry}
        material={materials['Material.038']}
        position={[-35.396, -0.04, 310.762]}
        rotation={[-0.249, 0, 0]}
        scale={[0.487, 0.343, 0.456]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048.geometry}
        material={materials['Material.039']}
        position={[-35.393, 0.144, 311.194]}
        rotation={[-0.62, 0, 0]}
        scale={[0.646, 0.591, 0.786]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049.geometry}
        material={materials['Material.040']}
        position={[-35.432, -0.217, 311.9]}
        rotation={[-2.113, 0.05, 3.067]}
        scale={[0.481, 0.339, 0.451]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube050.geometry}
        material={materials['Material.041']}
        position={[-35.393, 0.093, 312.186]}
        rotation={[-2.522, 0, -Math.PI]}
        scale={[0.646, 0.591, 0.786]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube051.geometry}
        material={materials['Material.042']}
        position={[-35.402, 0.014, 310.225]}
        rotation={[-0.141, 0, 0]}
        scale={[0.721, 0.839, 0.839]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube052.geometry}
        material={materials['Material.043']}
        position={[-35.41, 0.227, 313.044]}
        rotation={[-3.041, 0, -Math.PI]}
        scale={0.643}
      />
        </group>
        <group position={TREE_OFFSET_FROM_BASE}>
          {ROOT_MESHES.map((rootMesh) => (
            <TreeRootFillMesh
              key={rootMesh.node}
              castShadow
              receiveShadow
              fillProgress={rootsFillProgress}
              geometry={nodes[rootMesh.node].geometry}
              material={materials[rootMesh.material]}
              position={rootMesh.position}
              rotation={rootMesh.rotation}
              scale={rootMesh.scale}
            />
          ))}
        </group>
        <group position={TREE_OFFSET_FROM_BASE}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trunk003.geometry}
        material={materials['Trunk.001']}
        position={[-35.432, 4.358, 311.575]}
        scale={[0.228, 2.447, 0.228]}
      />
        </group>
        <group ref={leavesGroupRef}>
          <group position={TREE_OFFSET_FROM_BASE}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere069.geometry}
        material={materials['Leaves.038']}
        position={[-37.328, 6.162, 311.464]}
        rotation={[1.969, -1.188, 1.452]}
        scale={[0.46, 0.451, 0.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere070.geometry}
        material={materials['Leaves.038']}
        position={[-33.35, 8.422, 311.312]}
        rotation={[-2.764, -0.495, -1.827]}
        scale={[0.484, 0.475, 0.358]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere071.geometry}
        material={materials['Leaves.038']}
        position={[-35.341, 10.193, 311.447]}
        rotation={[Math.PI, -1.415, Math.PI]}
        scale={[0.626, 0.626, 0.387]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leaves11.geometry}
        material={materials['Leaves.038']}
        position={[-34.956, 8.92, 313.3]}
        rotation={[0.814, -0.745, -0.219]}
        scale={[0.398, 0.39, 0.294]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leaves9.geometry}
        material={materials['Leaves.038']}
        position={[-35.48, 5.581, 314.365]}
        rotation={[1.291, -1.144, -2.712]}
        scale={[0.5, 0.49, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leaves10.geometry}
        material={materials['Leaves.038']}
        position={[-35.904, 7.31, 309.534]}
        rotation={[1.958, -1.156, 2.809]}
        scale={[0.482, 0.472, 0.356]}
      />
          </group>
        </group>
        <group position={TREE_OFFSET_FROM_BASE}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Branch9.geometry}
        material={materials['Trunk.001']}
        position={[-35.432, 4.358, 311.575]}
        scale={[0.228, 2.447, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Branch10.geometry}
        material={materials['Trunk.001']}
        position={[-35.432, 4.358, 311.575]}
        scale={[0.228, 2.447, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Branch11.geometry}
        material={materials['Trunk.001']}
        position={[-35.432, 4.358, 311.575]}
        scale={[0.228, 2.447, 0.228]}
      />
        </group>
      </group>
    </group>
  );
}

export { TreeSmallV2 as Model };

useGLTF.preload(TREE_SMALL_V2_MODEL_PATH);