/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type { ThreeElements } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { Mesh, MeshStandardMaterial } from "three";
import { useLeafRustleAnimation } from "@/components/scene/useLeafRustleAnimation";
import {
  TreeRootFillMesh,
  type TreeRootMeshConfig,
} from "./TreeRootFillMesh";

const TREE_MEDIUM_MODEL_PATH = "/models/tree_medium.glb";
const TREE_BASE_POSITION: [number, number, number] = [-34.921, 0, 466.79];
const TREE_OFFSET_FROM_BASE: [number, number, number] = [34.921, 0, -466.79];

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>;
  materials: Record<string, MeshStandardMaterial>;
};

type TreeMediumProps = ThreeElements["group"] & {
  growthScale?: number;
  hideRoots?: boolean;
  rootsFillProgress?: number;
  rustleIntensity?: number;
};

const ROOT_MESHES: TreeRootMeshConfig[] = [
  { node: "Cube057", material: "Material.046", position: [-35.438, -0.729, 469.688], rotation: [0.489, 0, -Math.PI], scale: [-0.335, -0.226, -0.309] },
  { node: "Cube060", material: "Material.049", position: [-35.487, -0.678, 468.157], rotation: [-0.803, 0, 0], scale: [0.23, 0.162, 0.215] },
  { node: "Cube062", material: "Material.051", position: [-35.462, -0.427, 467.391], rotation: [-0.685, 0, 0], scale: [0.217, 0.147, 0.2] },
  { node: "Cube065", material: "Material.054", position: [-35.401, -0.427, 463.096], rotation: [-0.155, 0, 0], scale: [0.335, 0.226, 0.309] },
  { node: "Cube067", material: "Material.056", position: [-35.396, -0.639, 466.548], rotation: [-1.054, 0, 0], scale: [0.524, 0.369, 0.491] },
  { node: "Cube068", material: "Material.057", position: [-35.347, -0.421, 464.985], rotation: [-0.694, 0, 0], scale: [0.644, 0.435, 0.593] },
  { node: "Cube069", material: "Material.058", position: [-35.353, -0.772, 468.464], rotation: [-2.73, 0, -Math.PI], scale: 0.581 },
  { node: "Cube070", material: "Material.059", position: [-35.362, -0.039, 463.606], rotation: [0.378, 0, 0], scale: 0.712 },
  { node: "Cube071", material: "Material.060", position: [-35.363, -0.037, 469.81], rotation: [2.84, 0, Math.PI], scale: 0.667 },
  { node: "Cube072", material: "Material.061", position: [-35.393, -0.127, 465.791], rotation: [-0.249, 0, 0], scale: [0.524, 0.369, 0.491] },
  { node: "Cube073", material: "Material.062", position: [-35.348, 0.016, 466.257], rotation: [-0.62, 0, 0], scale: [0.904, 0.637, 0.847] },
  { node: "Cube074", material: "Material.063", position: [-35.435, -0.389, 467.062], rotation: [-2.113, 0.05, 3.067], scale: [0.547, 0.385, 0.512] },
  { node: "Cube075", material: "Material.064", position: [-35.347, -0.037, 467.386], rotation: [-2.522, 0, -Math.PI], scale: [0.893, 0.629, 0.836] },
  { node: "Cube076", material: "Material.065", position: [-35.347, -0.039, 465.14], rotation: [-0.141, 0, 0], scale: 0.935 },
  { node: "Cube077", material: "Material.066", position: [-35.41, 0.115, 468.362], rotation: [-3.041, 0, -Math.PI], scale: 0.73 },
  { node: "Cube078", material: "Material.067", position: [-35.347, 0.027, 469.098], rotation: [Math.PI, 0, Math.PI], scale: 0.906 },
  { node: "Cube079", material: "Material.068", position: [-35.347, -0.039, 464.438], scale: 0.935 },
];

export function TreeMedium({
  growthScale = 1,
  hideRoots = false,
  rootsFillProgress = 0,
  rustleIntensity = 0,
  ...props
}: TreeMediumProps) {
  const { nodes, materials } = useGLTF(
    TREE_MEDIUM_MODEL_PATH,
  ) as unknown as GLTFResult;
  const leavesGroupRef = useLeafRustleAnimation({
    intensity: rustleIntensity,
    phaseOffset: 2.1,
  });

  return (
    <group {...props} dispose={null}>
      <group position={TREE_BASE_POSITION} scale={growthScale}>
        <group position={TREE_OFFSET_FROM_BASE} visible={false}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057.geometry}
        material={materials['Material.046']}
        position={[-35.438, -0.729, 469.688]}
        rotation={[0.489, 0, -Math.PI]}
        scale={[-0.335, -0.226, -0.309]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube060.geometry}
        material={materials['Material.049']}
        position={[-35.487, -0.678, 468.157]}
        rotation={[-0.803, 0, 0]}
        scale={[0.23, 0.162, 0.215]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062.geometry}
        material={materials['Material.051']}
        position={[-35.462, -0.427, 467.391]}
        rotation={[-0.685, 0, 0]}
        scale={[0.217, 0.147, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube065.geometry}
        material={materials['Material.054']}
        position={[-35.401, -0.427, 463.096]}
        rotation={[-0.155, 0, 0]}
        scale={[0.335, 0.226, 0.309]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube067.geometry}
        material={materials['Material.056']}
        position={[-35.396, -0.639, 466.548]}
        rotation={[-1.054, 0, 0]}
        scale={[0.524, 0.369, 0.491]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube068.geometry}
        material={materials['Material.057']}
        position={[-35.347, -0.421, 464.985]}
        rotation={[-0.694, 0, 0]}
        scale={[0.644, 0.435, 0.593]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069.geometry}
        material={materials['Material.058']}
        position={[-35.353, -0.772, 468.464]}
        rotation={[-2.73, 0, -Math.PI]}
        scale={0.581}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube070.geometry}
        material={materials['Material.059']}
        position={[-35.362, -0.039, 463.606]}
        rotation={[0.378, 0, 0]}
        scale={0.712}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube071.geometry}
        material={materials['Material.060']}
        position={[-35.363, -0.037, 469.81]}
        rotation={[2.84, 0, Math.PI]}
        scale={0.667}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube072.geometry}
        material={materials['Material.061']}
        position={[-35.393, -0.127, 465.791]}
        rotation={[-0.249, 0, 0]}
        scale={[0.524, 0.369, 0.491]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube073.geometry}
        material={materials['Material.062']}
        position={[-35.348, 0.016, 466.257]}
        rotation={[-0.62, 0, 0]}
        scale={[0.904, 0.637, 0.847]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube074.geometry}
        material={materials['Material.063']}
        position={[-35.435, -0.389, 467.062]}
        rotation={[-2.113, 0.05, 3.067]}
        scale={[0.547, 0.385, 0.512]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube075.geometry}
        material={materials['Material.064']}
        position={[-35.347, -0.037, 467.386]}
        rotation={[-2.522, 0, -Math.PI]}
        scale={[0.893, 0.629, 0.836]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube076.geometry}
        material={materials['Material.065']}
        position={[-35.347, -0.039, 465.14]}
        rotation={[-0.141, 0, 0]}
        scale={0.935}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube077.geometry}
        material={materials['Material.066']}
        position={[-35.41, 0.115, 468.362]}
        rotation={[-3.041, 0, -Math.PI]}
        scale={0.73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube078.geometry}
        material={materials['Material.067']}
        position={[-35.347, 0.027, 469.098]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.906}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube079.geometry}
        material={materials['Material.068']}
        position={[-35.347, -0.039, 464.438]}
        scale={0.935}
      />
        </group>
        {!hideRoots && (
          <group position={TREE_OFFSET_FROM_BASE}>
            {ROOT_MESHES.map((rootMesh) => (
              <TreeRootFillMesh
                key={rootMesh.node}
                castShadow
                receiveShadow
                fillProgress={rootsFillProgress}
                geometry={nodes[rootMesh.node].geometry}
                material={materials[rootMesh.material]}
                position={rootMesh.position}
                rotation={rootMesh.rotation}
                scale={rootMesh.scale}
              />
            ))}
          </group>
        )}
        <group position={TREE_OFFSET_FROM_BASE}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trunk004.geometry}
        material={materials['Trunk.001']}
        position={[-34.921, 2.831, 466.79]}
        scale={1.131}
      />
        </group>
        <group ref={leavesGroupRef}>
          <group position={TREE_OFFSET_FROM_BASE}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leaves13.geometry}
        material={materials['Leaves.038']}
        position={[-33.874, 10.237, 462.456]}
        rotation={[2.874, -1.419, -2.478]}
        scale={[0.924, 0.907, 0.684]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leaves14.geometry}
        material={materials['Leaves.038']}
        position={[-36.794, 12.247, 471.105]}
        rotation={[1.046, -0.507, 1.265]}
        scale={[0.663, 0.663, 0.41]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leaves12.geometry}
        material={materials['Leaves.038']}
        position={[-39.731, 12.527, 468.578]}
        rotation={[1.969, -1.188, 1.452]}
        scale={[1.074, 1.054, 0.795]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leaves15.geometry}
        material={materials['Leaves.038']}
        position={[-36.786, 12.806, 462.637]}
        rotation={[-0.361, -0.549, 0.671]}
        scale={[0.694, 0.681, 0.514]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere079.geometry}
        material={materials['Leaves.038']}
        position={[-38.66, 12.73, 465.105]}
        rotation={[Math.PI, -1.415, Math.PI]}
        scale={[0.533, 0.533, 0.329]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere080.geometry}
        material={materials['Leaves.038']}
        position={[-33.091, 12.085, 472.593]}
        rotation={[-2.657, -1.297, -Math.PI]}
        scale={[1.231, 1.208, 0.911]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leaves17.geometry}
        material={materials['Leaves.038']}
        position={[-29.89, 12.689, 463.489]}
        rotation={[0, -1.002, 0]}
        scale={[0.846, 1.15, 0.846]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere082.geometry}
        material={materials['Leaves.038']}
        position={[-28.156, 12.842, 466.222]}
        scale={[0.732, 0.732, 0.452]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leaves16.geometry}
        material={materials['Leaves.038']}
        position={[-30.393, 12.085, 468.233]}
        rotation={[2.131, -1.297, -Math.PI]}
        scale={[0.955, 0.937, 0.707]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere084.geometry}
        material={materials['Leaves.038']}
        position={[-34.774, 14.339, 466.724]}
        scale={1.324}
      />
          </group>
        </group>
        <group position={TREE_OFFSET_FROM_BASE}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Branch12.geometry}
        material={materials['Trunk.001']}
        position={[-34.921, 2.831, 466.79]}
        scale={1.131}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Branch13.geometry}
        material={materials['Trunk.001']}
        position={[-34.921, 2.831, 466.79]}
        scale={1.131}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Branch14.geometry}
        material={materials['Trunk.001']}
        position={[-34.921, 2.831, 466.79]}
        scale={1.131}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Branch15.geometry}
        material={materials['Trunk.001']}
        position={[-34.921, 2.831, 466.79]}
        scale={1.131}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Branch16.geometry}
        material={materials['Trunk.001']}
        position={[-34.921, 2.831, 466.79]}
        scale={1.131}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Branch17.geometry}
        material={materials['Trunk.001']}
        position={[-34.921, 2.831, 466.79]}
        scale={1.131}
      />
        </group>
      </group>
    </group>
  );
}

export { TreeMedium as Model };

useGLTF.preload(TREE_MEDIUM_MODEL_PATH);